--TASK 1:
SELECT MIN(YEAR_FOUNDED), MAX(YEAR_FOUNDED)
FROM BUSINESSES

--TASK 2:
SELECT COUNT(*)
FROM BUSINESSES
WHERE YEAR_FOUNDED < 1000

--TASK 3:
SELECT *
FROM BUSINESSES
WHERE YEAR_FOUNDED < 1000
ORDER BY YEAR_FOUNDED ASC

--TASK 4:
SELECT B.BUSINESS, B.YEAR_FOUNDED, B.COUNTRY_CODE , C.CATEGORY
FROM BUSINESSES AS B
INNER JOIN CATEGORIES AS C
USING(CATEGORY_CODE)
WHERE YEAR_FOUNDED < 1000
ORDER BY B.YEAR_FOUNDED ASC

--TASK 5:
SELECT CATEGORY,COUNT(*) AS N
FROM CATEGORIES
INNER JOIN BUSINESSES
USING(CATEGORY_CODE)
GROUP BY CATEGORY
ORDER BY 2 DESC
LIMIT 10

--TASK 6:
SELECT MIN(B.YEAR_FOUNDED) AS OLDEST, C.CONTINENT
FROM BUSINESSES AS B
INNER JOIN COUNTRIES AS C
USING(COUNTRY_CODE)
GROUP BY 2
ORDER BY 1 ASC

--TASK 7:
SELECT B.BUSINESS, B.YEAR_FOUNDED, CA.CATEGORY, CO.COUNTRY, CO.CONTINENT
FROM CATEGORIES AS CA
INNER JOIN BUSINESSES AS B
USING(CATEGORY_CODE)
INNER JOIN COUNTRIES AS CO
USING(COUNTRY_CODE)

--TASK 8:
SELECT CO.CONTINENT, CA.CATEGORY,COUNT(B.BUSINESS) AS N
FROM CATEGORIES AS CA
INNER JOIN BUSINESSES AS B
USING(CATEGORY_CODE)
INNER JOIN COUNTRIES AS CO
USING(COUNTRY_CODE)
GROUP BY 1,2

--TASK 9:
SELECT CO.CONTINENT, CA.CATEGORY,COUNT(B.BUSINESS) AS N
FROM CATEGORIES AS CA
INNER JOIN BUSINESSES AS B
USING(CATEGORY_CODE)
INNER JOIN COUNTRIES AS CO
USING(COUNTRY_CODE)
GROUP BY 1,2
HAVING COUNT(B.BUSINESS) > 5
ORDER BY 3 DESC